# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dba', models.BooleanField(default=False)),
                ('ownico', models.BooleanField(default=False)),
                ('other', models.CharField(default=None, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idhash', models.CharField(max_length=1024, unique=True)),
                ('street1', models.CharField(default=None, max_length=255, null=True)),
                ('street2', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('zipcode', models.IntegerField(default=None, null=True)),
                ('zip4', models.IntegerField(default=None, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('parid', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('idhash', models.CharField(max_length=1024, unique=True)),
                ('street1', models.CharField(default=None, max_length=255, null=True)),
                ('street2', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('zipcode', models.IntegerField(default=None, null=True)),
                ('zip4', models.IntegerField(default=None, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterIndexTogether(
            name='property',
            index_together=set([('uid', 'county')]),
        ),
        migrations.AddField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(to='api.Property'),
        ),
    ]
