# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(blank=True, default=list, to='api.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('parid', 'county')]),
        ),
        migrations.AlterIndexTogether(
            name='property',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='property',
            name='uid',
        ),
    ]
