# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


def hashify_existing_addresses(apps, schema_editor):
    from api.models import PropertyAddress, OwnerAddress
    for pa in PropertyAddress.objects.all():
        pa.save()
    for oa in OwnerAddress.objects.all():
        oa.save()


def hashify_existing_addresses_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160430_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=None)),
                ('tax_type', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
            ],
        ),
        migrations.CreateModel(
            name='LienAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('tax_year', models.IntegerField()),
                ('winning_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Property')),
            ],
        ),
        migrations.AlterField(
            model_name='owneraddress',
            name='idhash',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='idhash',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='lienauction',
            unique_together=set([('property', 'tax_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('property', 'tax_year', 'tax_type', 'effective_date', 'amount', 'balance')]),
        ),
        migrations.RunPython(hashify_existing_addresses,
                             hashify_existing_addresses_reverse),
    ]
