# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField(default=None)),
                ('tax_type', models.CharField(max_length=64)),
                ('effective_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LienAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('tax_year', models.IntegerField()),
                ('winning_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dba', models.BooleanField(default=False)),
                ('ownico', models.BooleanField(default=False)),
                ('other', models.CharField(default=None, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idhash', models.CharField(editable=False, max_length=128, unique=True)),
                ('street1', models.CharField(default=None, max_length=255, null=True)),
                ('street2', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('zipcode', models.IntegerField(default=None, null=True)),
                ('zip4', models.IntegerField(default=None, null=True)),
                ('standardized', models.CharField(default=None, max_length=255, null=True)),
                ('tiger_line_id', models.CharField(default=None, max_length=16, null=True)),
                ('tiger_line_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default=None, max_length=1, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='prop.Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parid', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idhash', models.CharField(editable=False, max_length=128, unique=True)),
                ('street1', models.CharField(default=None, max_length=255, null=True)),
                ('street2', models.CharField(default=None, max_length=255, null=True)),
                ('city', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('zipcode', models.IntegerField(default=None, null=True)),
                ('zip4', models.IntegerField(default=None, null=True)),
                ('standardized', models.CharField(default=None, max_length=255, null=True)),
                ('tiger_line_id', models.CharField(default=None, max_length=16, null=True)),
                ('tiger_line_side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default=None, max_length=1, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='prop.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set([('parid', 'county')]),
        ),
        migrations.AddField(
            model_name='owner',
            name='properties',
            field=models.ManyToManyField(blank=True, default=list, to='prop.Property'),
        ),
        migrations.AddField(
            model_name='lienauction',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Property'),
        ),
        migrations.AddField(
            model_name='account',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop.Property'),
        ),
        migrations.AlterUniqueTogether(
            name='lienauction',
            unique_together=set([('property', 'tax_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('property', 'tax_year', 'tax_type', 'effective_date', 'amount', 'balance')]),
        ),
    ]
