# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0002_auto_20160504_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneraddress',
            name='zip4',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='owneraddress',
            name='zipcode',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='zip4',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='zipcode',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
