# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_auto_20160808_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneraddress',
            name='idhash',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='idhash',
            field=models.CharField(editable=False, max_length=128, null=True, unique=True),
        ),
    ]
