# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import prop.middleware


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    County = apps.get_model("prop", "County")
    grand = County.objects.create(name='grand', display_name='Grand')
    model_names = ['Property', 'Owner', 'PropertyAddress', 'OwnerAddress', 'Account', 'LienAuction']
    for m in model_names:
        model = apps.get_model("prop", m)
        model.objects.using(db_alias).all().update(county=grand)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0006_auto_20170715_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='county',
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AddField(
            model_name='account',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AddField(
            model_name='lienauction',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AddField(
            model_name='owner',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AddField(
            model_name='owneraddress',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AddField(
            model_name='propertyaddress',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id, null=True, on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='account',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AlterField(
            model_name='lienauction',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AlterField(
            model_name='owneraddress',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='county',
            field=models.ForeignKey(default=prop.middleware.get_current_county_id,
                                    on_delete=django.db.models.deletion.CASCADE, to='prop.County'),
        ),
    ]
