# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_auto_20170717_0412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('parid', 'county')},
        ),
    ]
