# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0008_auto_20170718_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaddress',
            name='idhash',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='propertyaddress',
            unique_together={('idhash', 'property')},
        ),
    ]
